version: 2.1
jobs:
  build:
    docker:
      - image: ghcr.io/sanju0910/ubuntu:latest
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
